import { describe, expect, it } from "vitest";

import {
  duplicatePayDaysOf,
  isPayrollSummaryCategory,
  parsePayrollSummaryText,
} from "./payrollSummary";

// 真实 payroll summary PDF(Payroll Journal Report)经 pdf-parse 抽出的文本,原样粘贴。
// 多列表格被压成一行行文本,Employee/Employer 两列的 Total 混在一起 —— 正是要处理的情况。
const REAL_TEXT = `

1/1
Employee Earnings
Off Cycle Payroll Pay day: 07/14/2026
Employee
Information
EmploymentEarningsDeductions/ContributionsEmployee TaxesEmployer TaxesTotals
Employee
Type
PaymentJobDescriptionHoursRateTotalDescription
Employee
Deduction
Employer
Contribution
DescriptionAmountDescriptionAmountDescriptionAmount
Meng, Bin
Paid by the
hour
Direct
Deposit
Technical
Product Analyst
Regular40.00$25.00$1,000.00
Federal Income
Tax
$38.08
Social
Security
$62.00Net Pay$860.82
TechTotalsGross$1,000.00Social Security$62.00Medicare$14.50
Check
Amount
$860.82
235 Grand St,
Jersey City, NJ
07302
Medicare$14.50FUTA$6.00
Employer
Cost
$1,117.33
NJ State Tax$16.15
NJ Employer
SUI
$28.65
NJ Employee SUI$4.25NJ WF/SWF$1.18
NJ Family Leave
Insurance
$2.30
NJ Employer
SDI
$5.00
NJ Employee SDI$1.90Total$117.33
Total$139.18
Payroll Totals
Technical
Product Analyst
Regular40.00$25.00$1,000.00
Federal Income
Tax
$38.08
Social
Security
$62.00Net Pay$860.82
TotalsGross$1,000.00Social Security$62.00Medicare$14.50
Check
Amount
$860.82
Medicare$14.50FUTA$6.00
Employer
Cost
$1,117.33
NJ State Tax$16.15
NJ Employer
SUI
$28.65
NJ Employee SUI$4.25NJ WF/SWF$1.18
NJ Family Leave
Insurance
$2.30
NJ Employer
SDI
$5.00
NJ Employee SDI$1.90Total$117.33
Total$139.18
Report generated by
Payroll Journal Report
Off Cycle Payroll
Report Created On: 07/08/2026
AndyXiongZheng LLC
30 N Gould St
Sheridan, WY 82801`;

describe("parsePayrollSummaryText", () => {
  const parsed = parsePayrollSummaryText(REAL_TEXT);

  it("读出 Employer Taxes 合计(= Employer Cost − Gross)", () => {
    expect(parsed.employerTaxTotal).toBe(117.33);
    expect(parsed.gross).toBe(1000);
    expect(parsed.employerCost).toBe(1117.33);
  });

  it("不会误取 Employee Taxes 的 Total($139.18)", () => {
    expect(parsed.employerTaxTotal).not.toBe(139.18);
  });

  it("与 PDF 里的 Total$117.33 交叉验证通过", () => {
    expect(parsed.matchedTotalLine).toBe(true);
  });

  it("读出发薪日与批次类型", () => {
    expect(parsed.payDay).toBe("07/14/2026");
    expect(parsed.payrollType).toBe("Off Cycle Payroll");
  });

  it("没有 Payroll Totals 小节时退回全文解析", () => {
    const noTotals = REAL_TEXT.slice(0, REAL_TEXT.indexOf("Payroll Totals"));
    const p = parsePayrollSummaryText(noTotals);
    expect(p.employerTaxTotal).toBe(117.33);
    expect(p.payDay).toBe("07/14/2026");
  });

  it("空文本 / 无关文本 → null,不瞎猜", () => {
    expect(parsePayrollSummaryText("").employerTaxTotal).toBeNull();
    expect(parsePayrollSummaryText("这是一份简历,没有薪资表").employerTaxTotal).toBeNull();
    // 只有 Gross 没有 Employer Cost 也不猜
    expect(parsePayrollSummaryText("TotalsGross$1,000.00Total$139.18").employerTaxTotal).toBeNull();
  });

  it("Employer Cost 等于 Gross(没有雇主税)时按识别失败处理", () => {
    expect(
      parsePayrollSummaryText("Payroll Totals Gross$1,000.00 Employer Cost $1,000.00").employerTaxTotal,
    ).toBeNull();
  });

  it("金额带千分位与换行都能解析", () => {
    const t = "Payroll Totals\nTotalsGross$12,345.67\nEmployer\nCost\n$13,000.00\nTotal$654.33";
    const p = parsePayrollSummaryText(t);
    expect(p.employerTaxTotal).toBe(654.33);
    expect(p.matchedTotalLine).toBe(true);
  });
});

describe("duplicatePayDaysOf", () => {
  it("发薪日各不相同 → 无重复", () => {
    expect(
      duplicatePayDaysOf([
        { payDay: "07/14/2026", employerTax: 117.33 },
        { payDay: "07/31/2026", employerTax: 117.33 },
      ]),
    ).toEqual([]);
  });
  it("同一发薪日两份 → 报出该发薪日(但不剔除,由用户核对)", () => {
    expect(
      duplicatePayDaysOf([
        { payDay: "07/14/2026", employerTax: 117.33 },
        { payDay: "07/14/2026", employerTax: 117.33 },
        { payDay: "07/31/2026", employerTax: 117.33 },
      ]),
    ).toEqual(["07/14/2026"]);
  });
  it("未识别金额的份数不参与判重", () => {
    expect(
      duplicatePayDaysOf([
        { payDay: "07/14/2026", employerTax: 117.33 },
        { payDay: "07/14/2026", employerTax: null },
      ]),
    ).toEqual([]);
  });
  it("没有发薪日的份数不参与判重", () => {
    expect(
      duplicatePayDaysOf([
        { payDay: null, employerTax: 10 },
        { payDay: null, employerTax: 20 },
      ]),
    ).toEqual([]);
  });
});

describe("isPayrollSummaryCategory", () => {
  it("忽略大小写与空格/下划线/连字符", () => {
    for (const c of ["payroll summary", "Payroll Summary", "PAYROLL_SUMMARY", "payroll-summary", "payrollsummary"]) {
      expect(isPayrollSummaryCategory(c)).toBe(true);
    }
  });
  it("不把别的分类当成 payroll summary", () => {
    for (const c of ["tax withheld reference", "i983", "offer", "resume", "payroll"]) {
      expect(isPayrollSummaryCategory(c)).toBe(false);
    }
  });
});
